### PR TITLE
Remarks for macOS users.

### PR DESCRIPTION
**Pull request by lenaschimmel**
Tried to use plottool on macOS for the first time yesterday. It worked, though I had some data transfer issues. They might as well be a symptom of the broken USB connector. Anyway, I think these instructions will help others to get startet more quickly on macOS.

@larsan relayed the info about tty device names to me.

### CODE REVIEW

**Comment by rohieb** [comment]
Yay, people who write the docs <3

**Comment by lenaschimmel** [comment]
Oooops. I messed up the link in the last paragraph. Should have used an editor with integrated markdown preview.

**Comment by ghost** [comment]
On Wed, Jun 27, 2018 at 06:44:18AM -0700, Lena Schimmel wrote:
> Oooops. I messed up the link in the last paragraph. Should have used an editor with integrated markdown preview.

I see nothing wrong with it?

**Comment by rohieb** [comment]
…besides the whitespace, which I have fixed just now.

**Pull request merged**
